# Generated by Django 3.2.1 on 2021-06-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210601_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidValue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
