# Generated by Django 3.2.1 on 2021-06-01 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bid_bidvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activelistings',
            name='price',
        ),
        migrations.AddField(
            model_name='newlisting',
            name='openbid',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='activelistings',
            name='name',
        ),
        migrations.AddField(
            model_name='activelistings',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auctions.newlisting'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='title',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='auctions.newlisting'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
