# Generated by Django 3.2.1 on 2021-06-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Books, Movies & Music', 'Books, Movies & Music'), ('Electronics', 'Electronics'), ('Collectibles & Art', 'Collectibles & Art'), ('Home & Garden', 'Home & Garden'), ('Sporting Goods', 'Sporting Goods'), ('Toys & Hobbies', 'Toys & Hobbies'), ('Business & Industrial', 'Business & Industrial'), ('Health & Beauty', 'Health & Beauty'), ('Others', 'Others')], default='', max_length=200),
            preserve_default=False,
        ),
    ]
