# Generated by Django 3.2.1 on 2021-06-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210602_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
