# Generated by Django 3.2.1 on 2021-06-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_newlisting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlisting',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
